import { Inter } from 'next/font/google'
import './globals.css'
import { cookies } from 'next/headers'
import Navbar from '@/components/parts/Navbar'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Mini Quiz',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const cookieJar = cookies()
  const token = cookieJar.get('token')
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar token={token} />
        {children}</body>
    </html>
  )
}
