version: '3'

networks:
  app-tier:
    driver: bridge

services:
  server:
    build: .
    networks:
      - app-tier
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:elephant@postgres:5432/mini-quiz?schema=public"
    ports:
      - 8000:8000

  postgres: 
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "elephant"
      POSTGRES_DB: "mini-quiz"
      POSTGRES_PORT: "5432"
    networks:
      - app-tier



